/*TO CHECK*/
DECLARE
    C_NAME CUSTOMERS.NAME%TYPE;
    C_ID CUSTOMERS.ID%TYPE;
    CURSOR C_CUSTOMERS IS
        SELECT ID,NAME FROM CUSTOMERS;
BEGIN
    OPEN C_CUSTOMERS;
    LOOP
    FETCH C_CUSTOMERS INTO C_ID,C_NAME;
        EXIT WHEN C_CUSTOMERS%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('CUSTOMER ('||C_ID||') IS '||C_NAME);
    END LOOP;
    CLOSE C_CUSTOMERS;
END;
/