DECLARE
    GRADE CHAR(1):='A';
BEGIN
    CASE GRADE
        WHEN 'A' THEN DBMS_OUTPUT.PUT_LINE('EXCELLENT');
        WHEN 'B' THEN DBMS_OUTPUT.PUT_LINE('VERY GOOD');
        WHEN 'C' THEN DBMS_OUTPUT.PUT_LINE('WELL DONE');
        WHEN 'D' THEN DBMS_OUTPUT.PUT_LINE('YOU PASSED');
        WHEN 'F' THEN DBMS_OUTPUT.PUT_LINE('BETTER TRY AGAIN');
        ELSE DBMS_OUTPUT.PUT_LINE('NO SUCH GRADE');
    END CASE;
END;
/