DECLARE
    A NUMBER(3):=100;
BEGIN
    IF(A=10) THEN
        DBMS_OUTPUT.PUT_LINE('VALUE OF A IS 10');
    ELSIF(A=20) THEN
        DBMS_OUTPUT.PUT_LINE('VALUE OF A IS 20');
    ELSIF(A=30) THEN
        DBMS_OUTPUT.PUT_LINE('VALUE OF A IS 30');
    ELSE
        DBMS_OUTPUT.PUT_LINE('NONE OF THE VALUES ARE MATCHING');
    END IF;
    DBMS_OUTPUT.PUT_LINE('EXACT VALUE OF A IS '||A);
END;
/