DECLARE
    A BOOLEAN:=TRUE;
    B BOOLEAN:=FALSE;
BEGIN
    IF(A AND B) THEN
        DBMS_OUTPUT.PUT_LINE('LINE 1 - CONDITON IS TRUE');
    END IF;
    IF(A OR B) THEN
        DBMS_OUTPUT.PUT_LINE('LINE 2 - CONDITION IS TRUE');
    END IF;
    IF(NOT A) THEN
        DBMS_OUTPUT.PUT_LINE('LINE 3 - A IS NOT TRUE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('LINE 3 - A IS TRUE');
    END IF;
    IF(NOT B) THEN
        DBMS_OUTPUT.PUT_LINE('LINE 4 - B IS NOT TRUE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('LINE 4 - B IS TRUE');
    END IF;
END;
/