/*CREATE TABLE BOOK(ACCESSION_NO INT,TITLE VARCHAR2(20),PUBLISHER VARCHAR2(20),AUTHOR VARCHAR2(20),STATUS VARCHAR2(20),DATE_OF_PURCHASE VARCHAR2(20));*/
CREATE OR REPLACE TRIGGER CHECKBOOK
BEFORE INSERT OR UPDATE ON BOOK FOR EACH ROW
DECLARE
    DOP BOOK.DATE_OF_PURCHASE%TYPE;
    YRS NUMBER;
BEGIN
    DOP := :NEW.DATE_OF_PURCHASE;
    YRS := (MONTHS_BETWEEN(SYSDATE,DOP))/12;
    IF (YRS > 20) THEN:
    NEW.STATUS := 'CANNOT BE ISSUED';
    DBMS_OUTPUT.PUT_LINE('STATUS : CANNOT BE ISSUED');
    END IF;
END;
/
