/*CREATE TABLE SB_ACCOUNT (ACCOUNT_NO NUMBER(10),CUSTOMER_NAME VARCHAR2(25),BALANCE NUMBER(10,2));
INSERT INTO SB_ACCOUNT(ACCOUNT_NO,CUSTOMER_NAME,BALANCE) VALUES (123,'JAISON DENNIS',5000);*/
DECLARE
    MCBAL NUMBER;
    MACT_NO NUMBER;
    WITHDRAW NUMBER ;
BEGIN
    MACT_NO:=&MACT_NO;
    SELECT BALANCE INTO MCBAL FROM SB_ACCOUNT WHERE ACCOUNT_NO=MACT_NO;
    WITHDRAW:=&WITHDRAW;
    MCBAL:=MCBAL-WITHDRAW;
    IF(MCBAL<1000) THEN
        DBMS_OUTPUT.PUT_LINE('WITHDRAWL NOT POSSIBLE.');
    ELSE
        UPDATE SB_ACCOUNT SET BALANCE=MCBAL WHERE ACCOUNT_NO=MACT_NO;
    END IF;
END;
/
