/*ERROR TO BE FIXED*/

CREATE OR REPLACE TRIGGER DISPLAY_SALARY_CHANGES
BEFORE DELETE OR INSERT OR UPDATE ON CUSTOMERS
FOR EACH ROW
WHEN (NEW.ID>0)
DECLARE
    SAL_DIFF NUMBER;
BEGIN
    SAL_DIFF:=:NEW.SALARY-:OLD.SALARY;
    DBMS_OUTPUT.PUT_LINE('OLD SALARY : ' || :OLD.SALARY);
    DBMS_OUTPUT.PUT_LINE('NEW SALARY : '|| :NEW.SALARY);
    DBMS_OUTPUT.PUT_LINE('SALARY DIFFERENCE : ',SAL_DIFF);
END;
/